"""
Executive Meeting PDF Report Generator matching Enterprise Briefing layout.
"""

import html
import json
import re
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether,
)

from ai_engine.config import (
    SUMMARY_FOLDER,
    TOPICS_FOLDER,
    ACTION_ITEMS_FOLDER,
    DECISIONS_FOLDER,
    OPEN_QUESTIONS_FOLDER,
    KEY_INSIGHTS_FOLDER,
    FUTURE_TOPICS_FOLDER,
    PDF_REPORT_FOLDER,
    REPORT_FOLDER,
)


class NumberedCanvas:
    """Canvas that adds standard confidential footer to every page."""

    def __init__(self, *args, **kwargs):
        pass


def add_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#64748B"))
    footer_text = "Confidential - For Internal Use Only | Generated by AI Synthesis Engine"
    canvas.drawCentredString(letter[0] / 2.0, 24, footer_text)
    canvas.restoreState()


class PDFReportGenerator:

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        self.title_style = ParagraphStyle(
            "ReportTitle",
            parent=self.styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#0B192C"),
            alignment=0,
            spaceAfter=6,
        )

        self.category_subtitle_style = ParagraphStyle(
            "CategorySubtitle",
            parent=self.styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
            alignment=0,
            spaceBefore=4,
            spaceAfter=6,
        )

        self.pill_left_style = ParagraphStyle(
            "PillLeft",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#1E293B"),
        )

        self.pill_right_style = ParagraphStyle(
            "PillRight",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#1E293B"),
            alignment=2,
        )

        self.section_heading_text_style = ParagraphStyle(
            "SectionHeadingText",
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#0B192C"),
        )

        self.sub_heading_style = ParagraphStyle(
            "SubHeading",
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=colors.HexColor("#1E293B"),
            spaceBefore=8,
            spaceAfter=4,
        )

        self.body_style = ParagraphStyle(
            "ExecutiveBody",
            parent=self.styles["BodyText"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=14.5,
            textColor=colors.HexColor("#334155"),
            spaceAfter=4,
        )

        self.bullet_style = ParagraphStyle(
            "ExecutiveBullet",
            parent=self.styles["BodyText"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=14.5,
            textColor=colors.HexColor("#1E293B"),
            leftIndent=14,
            firstLineIndent=-10,
            spaceAfter=5,
        )

        self.action_card_text_style = ParagraphStyle(
            "ActionCardText",
            parent=self.styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=14.5,
            textColor=colors.HexColor("#1E293B"),
        )

    def make_section_header(self, title_text):
        """Creates the signature blue-bar section header: | Title"""
        t = Table(
            [[
                "",
                Paragraph(f"<b>{html.escape(title_text)}</b>", self.section_heading_text_style)
            ]],
            colWidths=[4, 536]
        )
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#1D4ED8")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (1, 0), (1, 0), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("TOPPADDING", (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ]))
        return t

    def make_action_card(self, index, item):
        """Creates amber-bordered enterprise action card."""
        if isinstance(item, dict):
            owner = item.get("owner", "Not specified")
            task = item.get("task", "")
            deadline = item.get("deadline", "Not specified")
            priority = item.get("priority", "Medium")
            context = item.get("context", "")

            # Format: 1. Task Title & Scope - Owner (Dept/Role): Detailed instruction.
            p_content = f"<b>{index}. {html.escape(task)}</b>"
            p_content += f" - <b><font color='#1D4ED8'>{html.escape(owner)}</font></b>"
            if context:
                p_content += f": {html.escape(context)}"
            if deadline and str(deadline).lower() not in {"not specified", "n/a", "none", ""}:
                p_content += f" (Due: {html.escape(str(deadline))})"
        else:
            clean_text = re.sub(r"^[\s•\-\*\d\.]+", "", str(item)).strip()
            clean_text = re.sub(r"\*\*", "", clean_text).strip()
            p_content = f"<b>{index}. {html.escape(clean_text)}</b>"

        p = Paragraph(p_content, self.action_card_text_style)

        card_table = Table([[p]], colWidths=[540])
        card_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("LINEBEFORE", (0, 0), (0, -1), 3.5, colors.HexColor("#F59E0B")),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ]))
        return card_table

    def generate(self, output_name="meeting_001"):
        """Generates exact Enterprise Refined Meeting Summary PDF matching template."""
        PDF_REPORT_FOLDER.mkdir(parents=True, exist_ok=True)
        output = PDF_REPORT_FOLDER / f"{output_name}_report.pdf"

        # 1. Load Data from JSON report or processed text files
        json_report_file = REPORT_FOLDER / f"{output_name}_report.json"
        if json_report_file.exists():
            with open(json_report_file, "r", encoding="utf-8") as f:
                report_data = json.load(f)
            metadata = report_data.get("metadata", {})
            summary_raw = report_data.get("summary", "")
            topics_data = report_data.get("topics", [])
            actions_data = report_data.get("action_items", [])
            future_topics_data = report_data.get("future_topics", [])
        else:
            metadata = {"duration_minutes": "N/A"}
            summary_file = SUMMARY_FOLDER / f"{output_name}_summary.txt"
            summary_raw = summary_file.read_text(encoding="utf-8") if summary_file.exists() else ""
            topics_data = []
            actions_data = []
            future_topics_data = []

        document = SimpleDocTemplate(
            str(output),
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=40,
        )
        story = []

        # ── Document Header ──
        story.append(Paragraph("Refined Meeting Summary", self.title_style))
        story.append(Spacer(1, 4))

        duration_val = metadata.get("duration_minutes", "N/A") if isinstance(metadata, dict) else "N/A"
        pill_table = Table(
            [[
                Paragraph(f"<b>Meeting Duration:</b> {html.escape(str(duration_val))}", self.pill_left_style),
                Paragraph("<b>Generated by:</b> Enterprise Briefing AI", self.pill_right_style),
            ]],
            colWidths=[270, 270]
        )
        pill_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(pill_table)
        story.append(Spacer(1, 8))

        story.append(Paragraph("Executive Report", self.category_subtitle_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E1"), spaceAfter=14, spaceBefore=0))

        # ── Section 1: | Overview ──
        story.append(self.make_section_header("Overview"))
        story.append(Spacer(1, 6))
        story.append(Paragraph("This meeting focused on the following areas:", self.body_style))
        story.append(Spacer(1, 2))

        # Extract clean overview bullet points
        summary_clean = re.sub(r"^=+.*?=+\s*$", "", summary_raw, flags=re.MULTILINE).strip()
        overview_bullets = []
        for line in summary_clean.splitlines():
            line = re.sub(r"^[\s•\-\*\d\.]+", "", line).strip()
            line = re.sub(r"\*\*", "", line).strip()
            if line and len(line.split()) >= 3 and not line.lower().startswith("executive summary"):
                overview_bullets.append(line)

        if not overview_bullets:
            overview_bullets = [
                "Strategic Project Scoping and Deliverable Requirements",
                "Operational Execution, Resource Alignment, and Next Steps"
            ]

        for bullet in overview_bullets[:3]:
            story.append(Paragraph(f"&bull; &nbsp; {html.escape(bullet)}", self.bullet_style))

        story.append(Spacer(1, 8))

        # ── Section 2: | Discussion Points ──
        story.append(self.make_section_header("Discussion Points"))
        story.append(Spacer(1, 6))

        if topics_data:
            for idx, topic in enumerate(topics_data[:4], start=1):
                if isinstance(topic, dict):
                    title = topic.get("title", f"Topic {idx}")
                    details = topic.get("details", [])
                    story.append(Paragraph(f"<b>{idx}. {html.escape(title)}</b>", self.sub_heading_style))
                    for d in details[:3]:
                        clean_d = re.sub(r"^[\s•\-\*\d\.]+", "", str(d)).strip()
                        clean_d = re.sub(r"\*\*", "", clean_d).strip()
                        story.append(Paragraph(f"&bull; &nbsp; {html.escape(clean_d)}", self.bullet_style))
                else:
                    clean_item = re.sub(r"^[\s•\-\*\d\.]+", "", str(topic)).strip()
                    clean_item = re.sub(r"\*\*", "", clean_item).strip()
                    if " - " in clean_item:
                        parts = clean_item.split(" - ", 1)
                        story.append(Paragraph(f"<b>{idx}. {html.escape(parts[0].strip())}</b>", self.sub_heading_style))
                        story.append(Paragraph(f"&bull; &nbsp; {html.escape(parts[1].strip())}", self.bullet_style))
                    else:
                        story.append(Paragraph(f"&bull; &nbsp; {html.escape(clean_item)}", self.bullet_style))
                story.append(Spacer(1, 3))
        else:
            story.append(Paragraph("<i>Discussion points were analyzed and summarized from key meeting context.</i>", self.body_style))

        story.append(Spacer(1, 8))

        # ── Section 3: | Action Items ──
        story.append(self.make_section_header("Action Items"))
        story.append(Spacer(1, 6))

        # Clean actions list
        if isinstance(actions_data, str) and actions_data.strip().startswith(("[", "{")):
            try:
                actions_data = json.loads(actions_data)
            except Exception:
                pass

        clean_actions = []
        if isinstance(actions_data, list):
            for a in actions_data:
                if isinstance(a, str):
                    s = a.strip()
                    if s in {"[", "]", "{", "}", ",", ""}:
                        continue
                    if s.startswith(('"owner"', '"task"', '"deadline"', '"priority"')):
                        continue
                    clean_actions.append(s)
                elif isinstance(a, dict):
                    clean_actions.append(a)
        else:
            clean_actions = [actions_data]

        has_real_actions = False
        for a in clean_actions:
            if isinstance(a, dict):
                task = a.get("task", "")
                if task and "no action" not in task.lower() and len(task.split()) >= 3:
                    has_real_actions = True
                    break
            elif isinstance(a, str):
                if len(a.split()) >= 3 and "no action" not in a.lower():
                    has_real_actions = True
                    break

        if has_real_actions:
            for idx, act in enumerate(clean_actions[:5], start=1):
                story.append(self.make_action_card(idx, act))
                story.append(Spacer(1, 4))
        else:
            story.append(Paragraph("<i>No action items were assigned during this meeting.</i>", self.body_style))

        story.append(Spacer(1, 8))

        # ── Section 4: | Suggested Topics for Future Meetings ──
        story.append(self.make_section_header("Suggested Topics for Future Meetings"))
        story.append(Spacer(1, 6))

        if future_topics_data:
            for item in future_topics_data[:4]:
                clean_f = re.sub(r"^[\s•\-\*\d\.]+", "", str(item)).strip()
                clean_f = re.sub(r"\*\*", "", clean_f).strip()
                if clean_f:
                    story.append(Paragraph(f"&bull; &nbsp; {html.escape(clean_f)}", self.bullet_style))
        else:
            story.append(Paragraph("&bull; &nbsp; Reviewing follow-up progress and next milestone execution.", self.bullet_style))
            story.append(Paragraph("&bull; &nbsp; Finalizing operational roadmap and open action items.", self.bullet_style))

        story.append(Spacer(1, 14))

        # Build document with standard page footer
        document.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
        print(f"\n========== REFINED PDF REPORT GENERATED ==========\nSaved to: {output}\n")
        return str(output)


if __name__ == "__main__":
    generator = PDFReportGenerator()
    generator.generate()
